"""Touchstone (.s1p / .s2p) reading and writing.

Touchstone is the de-facto interchange format for measured / simulated
S-parameters, so being able to drop a real filter or amplifier ``.s2p`` into the
chain is what makes the frequency view useful with actual parts.

Supported:

* 1-port (``.s1p``) and 2-port (``.s2p``) files
* option line ``# <freq-unit> S <format> R <z0>`` with frequency units
  HZ/KHZ/MHZ/GHZ, formats DB / MA / RI, and an optional reference impedance
* ``!`` comments and blank lines

A 2-port data row is ``f  S11  S21  S12  S22`` (the classic Touchstone column
order), each S written as a pair according to the format.
"""

from __future__ import annotations

import math
from typing import List

import numpy as np

from .sparams import SParams

_FREQ_MULT = {"HZ": 1.0, "KHZ": 1e3, "MHZ": 1e6, "GHZ": 1e9}


def _pairs_to_complex(fmt: str, a: float, b: float) -> complex:
    fmt = fmt.upper()
    if fmt == "RI":
        return complex(a, b)
    if fmt == "MA":
        return a * np.exp(1j * math.radians(b))
    if fmt == "DB":
        return (10.0 ** (a / 20.0)) * np.exp(1j * math.radians(b))
    raise ValueError(f"unknown Touchstone format {fmt!r}")


def read_touchstone(path: str) -> SParams:
    """Read a .s1p or .s2p file into a two-port :class:`SParams`.

    A 1-port file is promoted to a two-port with the measured reflection on
    port 1, a perfect thru (S21 = S12 = 1) and a matched port 2, so it can be
    cascaded uniformly.
    """
    freq_mult = 1e9       # Touchstone default is GHz
    fmt = "MA"
    z0 = 50.0
    nums: List[float] = []

    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("!"):
                continue
            if line.startswith("#"):
                tokens = line[1:].upper().split()
                i = 0
                while i < len(tokens):
                    t = tokens[i]
                    if t in _FREQ_MULT:
                        freq_mult = _FREQ_MULT[t]
                    elif t in ("DB", "MA", "RI"):
                        fmt = t
                    elif t == "R" and i + 1 < len(tokens):
                        z0 = float(tokens[i + 1])
                        i += 1
                    # 'S' (parameter type) is assumed; G/Y/Z not supported.
                    i += 1
                continue
            # strip any inline comment
            if "!" in line:
                line = line.split("!", 1)[0]
            nums.extend(float(x) for x in line.replace(",", " ").split())

    if not nums:
        raise ValueError("no data found in Touchstone file")

    arr = np.asarray(nums, dtype=float)
    # Decide port count from the stride (1 + 2*n^2 values per frequency point).
    for ports, stride in ((2, 9), (1, 3)):
        if arr.size % stride == 0:
            n_ports = ports
            per = stride
            break
    else:
        raise ValueError("Touchstone row length is not 1- or 2-port shaped")

    rows = arr.reshape(-1, per)
    freqs = rows[:, 0] * freq_mult
    npts = rows.shape[0]
    s = np.zeros((npts, 2, 2), dtype=complex)

    if n_ports == 1:
        for k in range(npts):
            s[k, 0, 0] = _pairs_to_complex(fmt, rows[k, 1], rows[k, 2])
            s[k, 1, 0] = 1.0
            s[k, 0, 1] = 1.0
            s[k, 1, 1] = 0.0
    else:
        # column order: S11 S21 S12 S22
        order = [(0, 0), (1, 0), (0, 1), (1, 1)]
        for k in range(npts):
            for idx, (i, j) in enumerate(order):
                a = rows[k, 1 + 2 * idx]
                b = rows[k, 2 + 2 * idx]
                s[k, i, j] = _pairs_to_complex(fmt, a, b)

    order_idx = np.argsort(freqs)
    return SParams(freqs=freqs[order_idx], s=s[order_idx], z0=z0)


def write_touchstone(path: str, net: SParams, fmt: str = "DB") -> None:
    """Write a two-port :class:`SParams` as a .s2p file (DB / MA / RI)."""
    fmt = fmt.upper()
    lines = [
        "! Generated by RF Cascade Studio",
        f"# HZ S {fmt} R {net.z0:g}",
        "! freq            S11           S21           S12           S22",
    ]

    def _fmt_pair(z: complex) -> str:
        if fmt == "RI":
            return f"{z.real:14.6e} {z.imag:14.6e}"
        mag = abs(z)
        ang = math.degrees(math.atan2(z.imag, z.real))
        if fmt == "DB":
            db = 20.0 * math.log10(max(mag, 1e-12))
            return f"{db:14.6f} {ang:10.4f}"
        return f"{mag:14.6e} {ang:10.4f}"

    order = [(0, 0), (1, 0), (0, 1), (1, 1)]
    for k in range(net.n):
        cells = [f"{net.freqs[k]:14.0f}"]
        for (i, j) in order:
            cells.append(_fmt_pair(net.s[k, i, j]))
        lines.append("  ".join(cells))

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
